// frontend-svelte/src/lib/components/devices-drawer.svelte
<script lang="ts">
	// Svelte 5 runes port of
	// frontend/src/features/terminals/components/devices-drawer.tsx +
	// use-devices.ts. Lets an already-trusted device approve a new device's
	// pending request or revoke trust, without needing CLI access to the
	// VPS — the backend (/api/auth/devices) was already ported in Phase 2.
	//
	// Polling lives directly in this component as an $effect keyed on the
	// `open` prop, replacing the original's `useDevices(enabled)` hook —
	// there's only one consumer, so a shared module singleton (like
	// terminal-sessions.svelte.ts) would be the wrong shape here.
	import { Check, ShieldCheck, ShieldQuestion, Smartphone, Trash2, X } from 'lucide-svelte';

	import {
		fetchDevices,
		mutateDevice,
		relativeTime,
		type ApprovedDevice,
		type PendingDevice
	} from '$lib/features/terminals/devices';

	interface Props {
		open: boolean;
		onOpenChange: (open: boolean) => void;
	}

	let { open, onOpenChange }: Props = $props();

	const POLL_INTERVAL_MS = 8000;

	let approved = $state<Record<string, ApprovedDevice>>({});
	let pending = $state<Record<string, PendingDevice>>({});
	let loading = $state(false);
	let busy = $state<string | null>(null);
	let inflight = false;

	async function refresh(): Promise<void> {
		if (inflight) return;
		inflight = true;
		loading = true;
		try {
			const payload = await fetchDevices();
			if (payload) {
				approved = payload.approved ?? {};
				pending = payload.pending ?? {};
			}
		} finally {
			loading = false;
			inflight = false;
		}
	}

	// Poll only while the drawer is open, same as the original's `enabled` flag.
	$effect(() => {
		if (!open) return;
		void refresh();
		const id = window.setInterval(() => void refresh(), POLL_INTERVAL_MS);
		return () => window.clearInterval(id);
	});

	async function act(action: 'approve' | 'revoke', id: string, label?: string): Promise<void> {
		busy = id;
		try {
			const payload = await mutateDevice(action, id, label);
			if (payload) {
				approved = payload.approved ?? approved;
				pending = payload.pending ?? pending;
			} else {
				await refresh();
			}
		} finally {
			busy = null;
		}
	}

	let pendingEntries = $derived(
		Object.entries(pending).sort((a, b) => b[1].lastSeen - a[1].lastSeen)
	);
	let approvedEntries = $derived(
		Object.entries(approved).sort((a, b) => b[1].approvedAt - a[1].approvedAt)
	);
	let pendingCount = $derived(Object.keys(pending).length);
</script>

{#if open}
	<div
		class="devices-backdrop"
		role="presentation"
		onclick={() => onOpenChange(false)}
	>
		<div
			role="dialog"
			aria-modal="true"
			aria-label="Trusted devices"
			onclick={(event) => event.stopPropagation()}
			class="devices-sheet"
		>
			<div class="devices-header">
				<div class="devices-header__title">
					<ShieldCheck size={16} color="#7dd3fc" />
					<div>
						<p class="devices-header__label">Trusted devices</p>
						<p class="devices-header__hint">
							{pendingCount > 0
								? `${pendingCount} awaiting approval`
								: 'Approve or revoke devices that can sign in'}
						</p>
					</div>
				</div>
				<button
					type="button"
					onclick={() => onOpenChange(false)}
					class="devices-close"
					aria-label="Close devices"
				>
					<X size={16} />
				</button>
			</div>

			<div class="devices-body">
				<section>
					<p class="devices-section-label devices-section-label--warning">
						<ShieldQuestion size={14} /> Pending approval
					</p>
					{#if pendingEntries.length === 0}
						<p class="devices-empty">{loading ? 'Loading…' : 'No devices waiting.'}</p>
					{:else}
						<ul class="devices-list">
							{#each pendingEntries as [id, d] (id)}
								<li class="devices-item devices-item--pending">
									<Smartphone size={16} color="#fcd34d" />
									<div class="devices-item__body">
										<p class="devices-item__label">{d.label}</p>
										<p class="devices-item__id">{id}</p>
										<p class="devices-item__meta">
											ip {d.ip} · {d.attempts} attempt{d.attempts === 1 ? '' : 's'} ·
											{relativeTime(d.lastSeen)}
										</p>
									</div>
									<div class="devices-item__actions">
										<!-- Dismiss reuses revoke: revokeDevice() already deletes the
											pending record too, so no new endpoint is needed. It
											clears the request, it does not blocklist the device —
											the same id reappears here if it retries the password. -->
										<button
											type="button"
											disabled={busy === id}
											onclick={() => void act('revoke', id)}
											title="Clear this request. The device can ask again."
											class="devices-btn devices-btn--muted"
										>
											<X size={14} /> Dismiss
										</button>
										<button
											type="button"
											disabled={busy === id}
											onclick={() => void act('approve', id, d.label)}
											class="devices-btn devices-btn--approve"
										>
											<Check size={14} /> Approve
										</button>
									</div>
								</li>
							{/each}
						</ul>
					{/if}
				</section>

				<section>
					<p class="devices-section-label">
						<ShieldCheck size={14} /> Approved ({approvedEntries.length})
					</p>
					{#if approvedEntries.length === 0}
						<p class="devices-empty">No trusted devices yet.</p>
					{:else}
						<ul class="devices-list">
							{#each approvedEntries as [id, d] (id)}
								<li class="devices-item">
									<ShieldCheck size={16} color="#6ee7b7" />
									<div class="devices-item__body">
										<p class="devices-item__label">{d.label}</p>
										<p class="devices-item__id">{id}</p>
										<p class="devices-item__meta">
											approved {relativeTime(d.approvedAt)}
											{d.lastSeen ? ` · last seen ${relativeTime(d.lastSeen)}` : ''}
										</p>
									</div>
									<button
										type="button"
										disabled={busy === id}
										onclick={() => void act('revoke', id)}
										class="devices-icon-btn"
										aria-label="Revoke device"
										title="Revoke trust"
									>
										<Trash2 size={14} />
									</button>
								</li>
							{/each}
						</ul>
					{/if}
				</section>
			</div>
		</div>
	</div>
{/if}

<style>
	.devices-backdrop {
		position: fixed;
		inset: 0;
		z-index: 100;
		background: rgba(4, 8, 16, 0.6);
		display: flex;
		align-items: flex-end;
		justify-content: center;
	}
	@media (min-width: 640px) {
		.devices-backdrop {
			align-items: center;
		}
	}
	.devices-sheet {
		width: 100%;
		max-width: 28rem;
		max-height: 85vh;
		display: flex;
		flex-direction: column;
		background: var(--surface);
		border: 1px solid var(--border);
		border-radius: 1.25rem 1.25rem 0 0;
		overflow: hidden;
	}
	@media (min-width: 640px) {
		.devices-sheet {
			border-radius: 1.25rem;
			margin-bottom: 10vh;
		}
	}
	.devices-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 12px;
		border-bottom: 1px solid var(--border);
		padding: 12px 16px;
	}
	.devices-header__title {
		display: flex;
		align-items: center;
		gap: 8px;
	}
	.devices-header__label {
		margin: 0;
		font-size: 0.85rem;
		font-weight: 600;
		color: var(--ink);
	}
	.devices-header__hint {
		margin: 0;
		font-size: 0.68rem;
		color: var(--ink-muted);
	}
	.devices-close {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 32px;
		height: 32px;
		border-radius: 999px;
		border: 1px solid var(--border);
		color: var(--ink-muted);
	}
	.devices-body {
		overflow-y: auto;
		padding: 12px;
		display: flex;
		flex-direction: column;
		gap: 18px;
	}
	.devices-section-label {
		display: flex;
		align-items: center;
		gap: 6px;
		margin: 0 0 8px 4px;
		font-size: 0.68rem;
		font-weight: 600;
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--ink-muted);
	}
	.devices-section-label--warning {
		color: var(--warning);
	}
	.devices-empty {
		text-align: center;
		padding: 12px 8px;
		font-size: 0.75rem;
		color: var(--ink-muted);
	}
	.devices-list {
		list-style: none;
		margin: 0;
		padding: 0;
		display: flex;
		flex-direction: column;
		gap: 6px;
	}
	.devices-item {
		display: flex;
		align-items: center;
		gap: 8px;
		border-radius: 0.65rem;
		border: 1px solid var(--border);
		background: var(--surface-2);
		padding: 8px 10px;
	}
	.devices-item--pending {
		border-color: rgba(251, 191, 36, 0.3);
		background: rgba(251, 191, 36, 0.1);
	}
	.devices-item__body {
		min-width: 0;
		flex: 1;
	}
	.devices-item__label {
		margin: 0;
		font-size: 0.75rem;
		font-weight: 600;
		color: var(--ink);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}
	.devices-item__id {
		margin: 0;
		font-family: var(--font-mono);
		font-size: 0.62rem;
		color: var(--ink-muted);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}
	.devices-item__meta {
		margin: 0;
		font-size: 0.62rem;
		color: var(--ink-muted);
	}
	.devices-item__actions {
		display: flex;
		align-items: center;
		gap: 6px;
		flex-shrink: 0;
	}
	.devices-btn {
		display: inline-flex;
		align-items: center;
		gap: 4px;
		border-radius: 0.5rem;
		border: 1px solid var(--border);
		padding: 6px 10px;
		font-size: 0.72rem;
		font-weight: 500;
	}
	.devices-btn:disabled {
		opacity: 0.5;
	}
	.devices-btn--muted {
		color: var(--ink-muted);
		background: rgba(255, 255, 255, 0.04);
	}
	.devices-btn--approve {
		border-color: rgba(52, 211, 153, 0.4);
		background: rgba(52, 211, 153, 0.15);
		color: #a7f3d0;
	}
	.devices-icon-btn {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		flex-shrink: 0;
		width: 30px;
		height: 30px;
		border-radius: 0.5rem;
		border: 1px solid var(--border);
		color: var(--ink-muted);
	}
	.devices-icon-btn:hover {
		color: #fca5a5;
	}
</style>

// frontend/src/features/terminals/components/devices-drawer.tsx
'use client';

import { useState } from 'react';
import { Check, ShieldCheck, ShieldQuestion, Smartphone, Trash2, X } from 'lucide-react';

import { useDevices } from '@/features/terminals/hooks/use-devices';

export interface DevicesDrawerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

function relativeTime(ts: number): string {
  const diff = Date.now() - ts;
  const min = Math.round(diff / 60000);
  if (min < 1) return 'just now';
  if (min < 60) return `${min}m ago`;
  const hr = Math.round(min / 60);
  if (hr < 24) return `${hr}h ago`;
  return `${Math.round(hr / 24)}d ago`;
}

/**
 * In-app trusted-device manager. Lets an already-logged-in (already-trusted)
 * device approve a new device's pending request, or revoke trust — no CLI on
 * the box needed. Polls while open so a fresh request appears on its own.
 */
export function DevicesDrawer({ open, onOpenChange }: DevicesDrawerProps) {
  const { approved, pending, pendingCount, loading, approve, revoke } = useDevices(open);
  const [busy, setBusy] = useState<string | null>(null);

  if (!open) return null;

  async function act(fn: () => Promise<void>, id: string) {
    setBusy(id);
    try {
      await fn();
    } finally {
      setBusy(null);
    }
  }

  const pendingEntries = Object.entries(pending).sort((a, b) => b[1].lastSeen - a[1].lastSeen);
  const approvedEntries = Object.entries(approved).sort(
    (a, b) => b[1].approvedAt - a[1].approvedAt
  );

  return (
    <div className="launcher-drawer-backdrop" onClick={() => onOpenChange(false)}>
      <div
        role="dialog"
        aria-modal="true"
        aria-label="Trusted devices"
        onClick={(event) => event.stopPropagation()}
        className="launcher-drawer-sheet"
      >
        <div className="flex items-center justify-between gap-3 border-b border-border/70 px-4 py-3">
          <div className="flex items-center gap-2">
            <ShieldCheck className="h-4 w-4 text-sky-300" />
            <div>
              <p className="text-sm font-semibold text-foreground">Trusted devices</p>
              <p className="text-[11px] text-muted-foreground">
                {pendingCount > 0
                  ? `${pendingCount} awaiting approval`
                  : 'Approve or revoke devices that can sign in'}
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={() => onOpenChange(false)}
            className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-border/60 text-muted-foreground"
            aria-label="Close devices"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="max-h-[70vh] space-y-5 overflow-y-auto px-3 py-3">
          <section>
            <p className="mb-2 flex items-center gap-1.5 px-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-amber-300">
              <ShieldQuestion className="h-3.5 w-3.5" /> Pending approval
            </p>
            {pendingEntries.length === 0 ? (
              <p className="px-2 py-3 text-center text-xs text-muted-foreground">
                {loading ? 'Loading…' : 'No devices waiting.'}
              </p>
            ) : (
              <ul className="grid gap-1.5">
                {pendingEntries.map(([id, d]) => (
                  <li
                    key={id}
                    className="flex items-center gap-2 rounded-lg border border-amber-500/30 bg-amber-500/10 px-2.5 py-2"
                  >
                    <Smartphone className="h-4 w-4 shrink-0 text-amber-300" />
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-xs font-semibold text-amber-50">{d.label}</p>
                      <p className="truncate font-mono text-[10px] text-amber-100/70">{id}</p>
                      <p className="text-[10px] text-amber-100/60">
                        ip {d.ip} · {d.attempts} attempt{d.attempts === 1 ? '' : 's'} ·{' '}
                        {relativeTime(d.lastSeen)}
                      </p>
                    </div>
                    <div className="flex shrink-0 items-center gap-1.5">
                      {/* Dismiss reuses revoke: revokeDevice() already deletes the
                          pending record too, so no new endpoint is needed. It
                          clears the request, it does not blocklist the device —
                          the same id reappears here if it retries the password. */}
                      <button
                        type="button"
                        disabled={busy === id}
                        onClick={() => void act(() => revoke(id), id)}
                        title="Clear this request. The device can ask again."
                        className="inline-flex items-center gap-1 rounded-md border border-border bg-muted/40 px-2.5 py-1.5 text-[12px] font-medium text-muted-foreground disabled:opacity-50"
                      >
                        <X className="h-3.5 w-3.5" /> Dismiss
                      </button>
                      <button
                        type="button"
                        disabled={busy === id}
                        onClick={() => void act(() => approve(id, d.label), id)}
                        className="inline-flex items-center gap-1 rounded-md border border-emerald-500/40 bg-emerald-500/15 px-2.5 py-1.5 text-[12px] font-medium text-emerald-100 disabled:opacity-50"
                      >
                        <Check className="h-3.5 w-3.5" /> Approve
                      </button>
                    </div>
                  </li>
                ))}
              </ul>
            )}
          </section>

          <section>
            <p className="mb-2 flex items-center gap-1.5 px-1 text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">
              <ShieldCheck className="h-3.5 w-3.5" /> Approved ({approvedEntries.length})
            </p>
            {approvedEntries.length === 0 ? (
              <p className="px-2 py-3 text-center text-xs text-muted-foreground">
                No trusted devices yet.
              </p>
            ) : (
              <ul className="grid gap-1.5">
                {approvedEntries.map(([id, d]) => (
                  <li
                    key={id}
                    className="flex items-center gap-2 rounded-lg border border-border/50 bg-card/40 px-2.5 py-2"
                  >
                    <ShieldCheck className="h-4 w-4 shrink-0 text-emerald-300" />
                    <div className="min-w-0 flex-1">
                      <p className="truncate text-xs font-semibold text-foreground">{d.label}</p>
                      <p className="truncate font-mono text-[10px] text-muted-foreground">{id}</p>
                      <p className="text-[10px] text-muted-foreground">
                        approved {relativeTime(d.approvedAt)}
                        {d.lastSeen ? ` · last seen ${relativeTime(d.lastSeen)}` : ''}
                      </p>
                    </div>
                    <button
                      type="button"
                      disabled={busy === id}
                      onClick={() => void act(() => revoke(id), id)}
                      className="inline-flex h-8 w-8 shrink-0 items-center justify-center rounded-md border border-border/60 text-muted-foreground hover:text-rose-300 disabled:opacity-50"
                      aria-label="Revoke device"
                      title="Revoke trust"
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </button>
                  </li>
                ))}
              </ul>
            )}
          </section>
        </div>
      </div>
    </div>
  );
}
