// frontend/src/features/terminals/components/file-explorer-dialog.tsx
'use client';

import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ChevronRight, Folder, Home, Search, X } from 'lucide-react';

interface FsEntry {
  name: string;
  path: string;
  isDir: boolean;
}

interface FsListResult {
  path: string;
  parent: string | null;
  roots: Array<{ label: string; path: string }>;
  entries: FsEntry[];
}

export function FileExplorerDialog({
  open,
  onClose,
  onPick,
}: {
  open: boolean;
  onClose: () => void;
  onPick: (absolutePath: string) => void;
}) {
  const [result, setResult] = useState<FsListResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [query, setQuery] = useState('');

  const load = useCallback(async (target?: string) => {
    setLoading(true);
    setError(null);
    try {
      const url = target ? `/api/fs/list?path=${encodeURIComponent(target)}` : '/api/fs/list';
      const response = await fetch(url);
      const payload = (await response.json()) as FsListResult & { error?: string };
      if (!response.ok) throw new Error(payload.error || 'List failed');
      setResult(payload);
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : 'List failed');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    if (!open) return;
    setQuery('');
    void load();
  }, [open, load]);

  const filtered = useMemo(() => {
    if (!result) return [];
    const list = result.entries.filter((entry) => entry.isDir);
    if (!query.trim()) return list;
    const needle = query.trim().toLowerCase();
    return list.filter((entry) => entry.name.toLowerCase().includes(needle));
  }, [result, query]);

  if (!open) return null;

  const crumbs = result ? buildCrumbs(result.path, result.roots) : [];

  return (
    <div className="launcher-drawer-backdrop" onClick={onClose}>
      <div
        role="dialog"
        aria-modal="true"
        aria-label="File explorer"
        onClick={(event) => event.stopPropagation()}
        className="launcher-drawer-sheet"
      >
        <div className="flex items-center justify-between gap-3 border-b border-border/70 px-4 py-3">
          <div>
            <p className="text-sm font-semibold text-foreground">Change directory</p>
            <p className="text-[11px] text-muted-foreground">Browse home or projects. Pick a folder to cd into it.</p>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-border/60 text-muted-foreground"
            aria-label="Close explorer"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="space-y-2 border-b border-border/60 px-3 py-2">
          <div className="flex items-center gap-1.5">
            {result?.roots.map((root) => (
              <button
                key={root.path}
                type="button"
                onClick={() => void load(root.path)}
                className="fs-root-chip"
              >
                {root.label === 'Home' ? <Home className="h-3 w-3" /> : <Folder className="h-3 w-3" />}
                {root.label}
              </button>
            ))}
          </div>
          <div className="fs-search">
            <Search className="h-4 w-4 text-muted-foreground" />
            <input
              type="search"
              value={query}
              onChange={(event) => setQuery(event.target.value)}
              placeholder="Filter folders"
              className="fs-search-input"
            />
          </div>
          <div className="flex flex-wrap items-center gap-1 text-[11px] text-muted-foreground">
            {result?.parent ? (
              <button
                type="button"
                onClick={() => void load(result.parent ?? undefined)}
                className="fs-crumb-btn"
                title="Go up"
              >
                <ArrowLeft className="h-3 w-3" />
                Up
              </button>
            ) : null}
            {crumbs.map((crumb, index) => (
              <span key={crumb.path} className="flex items-center gap-1">
                {index > 0 ? <ChevronRight className="h-3 w-3 opacity-60" /> : null}
                <button
                  type="button"
                  onClick={() => void load(crumb.path)}
                  className="fs-crumb-btn"
                >
                  {crumb.label}
                </button>
              </span>
            ))}
          </div>
        </div>

        <div className="max-h-[60vh] overflow-y-auto p-3">
          {loading ? (
            <p className="py-6 text-center text-xs text-muted-foreground">Loading…</p>
          ) : error ? (
            <p className="py-6 text-center text-xs text-destructive">{error}</p>
          ) : filtered.length === 0 ? (
            <p className="py-6 text-center text-xs text-muted-foreground">No folders here</p>
          ) : (
            <ul className="grid gap-1.5">
              {filtered.map((entry) => (
                <li key={entry.path}>
                  {/* role=button div, not <button>: it nests the "cd here"
                      <button> below, and a button-in-button is invalid HTML
                      (React throws a hydration error on a fresh build). */}
                  <div
                    role="button"
                    tabIndex={0}
                    onClick={() => void load(entry.path)}
                    onDoubleClick={() => {
                      onPick(entry.path);
                      onClose();
                    }}
                    onKeyDown={(event) => {
                      if (event.key === 'Enter' || event.key === ' ') {
                        event.preventDefault();
                        void load(entry.path);
                      }
                    }}
                    className="fs-entry"
                  >
                    <Folder className="h-4 w-4 text-amber-300" />
                    <span className="flex-1 truncate text-sm font-medium text-foreground">{entry.name}</span>
                    <button
                      type="button"
                      onClick={(event) => {
                        event.stopPropagation();
                        onPick(entry.path);
                        onClose();
                      }}
                      className="fs-entry-cd"
                    >
                      cd here
                    </button>
                  </div>
                </li>
              ))}
            </ul>
          )}
        </div>

        {result ? (
          <div className="flex items-center justify-between gap-2 border-t border-border/70 px-3 py-2 text-[11px]">
            <span className="truncate font-mono text-muted-foreground" title={result.path}>
              {result.path}
            </span>
            <button
              type="button"
              onClick={() => {
                onPick(result.path);
                onClose();
              }}
              className="fs-cd-current"
            >
              cd here
            </button>
          </div>
        ) : null}
      </div>
    </div>
  );
}

function buildCrumbs(
  currentPath: string,
  roots: Array<{ label: string; path: string }>
): Array<{ label: string; path: string }> {
  const rootMatch = [...roots].sort((a, b) => b.path.length - a.path.length).find(
    (root) => currentPath === root.path || currentPath.startsWith(`${root.path}/`)
  );
  if (!rootMatch) return [{ label: currentPath, path: currentPath }];

  const relative = currentPath.slice(rootMatch.path.length).split('/').filter(Boolean);
  const crumbs: Array<{ label: string; path: string }> = [{ label: rootMatch.label, path: rootMatch.path }];
  let running = rootMatch.path;
  for (const segment of relative) {
    running = `${running}/${segment}`;
    crumbs.push({ label: segment, path: running });
  }
  return crumbs;
}

// frontend-svelte/src/lib/features/terminals/FileExplorerDialog.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { ArrowLeft, ChevronRight, Folder, Home, Search, X } from 'lucide-svelte';

	import { buildCrumbs, filterDirectories, type FsListResult } from './pane-tools';

	interface Props {
		onClose: () => void;
		onPick: (absolutePath: string) => void;
	}

	let { onClose, onPick }: Props = $props();
	let result = $state<FsListResult | null>(null);
	let loading = $state(false);
	let error = $state<string | null>(null);
	let query = $state('');
	let filtered = $derived(result ? filterDirectories(result.entries, query) : []);
	let crumbs = $derived(result ? buildCrumbs(result.path, result.roots) : []);

	async function load(target?: string): Promise<void> {
		loading = true;
		error = null;
		try {
			const suffix = target ? `?path=${encodeURIComponent(target)}` : '';
			const response = await fetch(`/api/fs/list${suffix}`);
			const payload = (await response.json().catch(() => ({}))) as FsListResult & { error?: string };
			if (!response.ok || !payload.path || !Array.isArray(payload.entries)) {
				throw new Error(payload.error ?? `Folder list failed (${response.status})`);
			}
			result = payload;
		} catch (caught) {
			error = caught instanceof Error ? caught.message : 'Folder list failed';
		} finally {
			loading = false;
		}
	}

	function pick(path: string): void {
		onPick(path);
		onClose();
	}

	onMount(() => void load());
</script>

<svelte:window onkeydown={(event) => event.key === 'Escape' && onClose()} />

<div
	class="fs-backdrop"
	role="presentation"
	onclick={(event) => {
		if (event.target === event.currentTarget) onClose();
	}}
>
	<div class="fs-sheet" role="dialog" aria-modal="true" aria-label="File explorer" tabindex="-1">
		<header class="fs-header">
			<div>
				<h2>Change directory</h2>
				<p>Browse allowed host folders and inject a safe <code>cd</code> command.</p>
			</div>
			<button type="button" class="fs-close" onclick={onClose} aria-label="Close explorer"><X size={16} /></button>
		</header>

		<div class="fs-toolbar">
			<div class="fs-roots">
				{#each result?.roots ?? [] as root (root.path)}
					<button type="button" onclick={() => void load(root.path)}>
						{#if root.label === 'Home'}<Home size={12} />{:else}<Folder size={12} />{/if}
						{root.label}
					</button>
				{/each}
			</div>
			<label class="fs-search">
				<Search size={14} />
				<input type="search" bind:value={query} placeholder="Filter folders" aria-label="Filter folders" />
			</label>
			<div class="fs-crumbs">
				{#if result?.parent}
					<button type="button" onclick={() => void load(result?.parent ?? undefined)} title="Go up"><ArrowLeft size={12} /> Up</button>
				{/if}
				{#each crumbs as crumb, index (crumb.path)}
					{#if index > 0}<ChevronRight size={11} />{/if}
					<button type="button" onclick={() => void load(crumb.path)}>{crumb.label}</button>
				{/each}
			</div>
		</div>

		<div class="fs-body">
			{#if loading}
				<p class="fs-empty">Loading…</p>
			{:else if error}
				<p class="fs-empty fs-empty--error">{error}</p>
			{:else if filtered.length === 0}
				<p class="fs-empty">No folders here.</p>
			{:else}
				<ul class="fs-list">
					{#each filtered as entry (entry.path)}
						<li>
							<div
								class="fs-entry"
								role="button"
								tabindex="0"
								onclick={() => void load(entry.path)}
								ondblclick={() => pick(entry.path)}
								onkeydown={(event) => {
									if (event.key === 'Enter' || event.key === ' ') {
										event.preventDefault();
										void load(entry.path);
									}
								}}
							>
								<Folder size={15} />
								<span>{entry.name}</span>
								<button type="button" onclick={(event) => { event.stopPropagation(); pick(entry.path); }}>cd here</button>
							</div>
						</li>
					{/each}
				</ul>
			{/if}
		</div>

		{#if result}
			<footer class="fs-footer">
				<span title={result.path}>{result.path}</span>
				<button type="button" onclick={() => pick(result!.path)}>cd here</button>
			</footer>
		{/if}
	</div>
</div>

<style>
	.fs-backdrop { position: fixed; inset: 0; z-index: 140; display: flex; align-items: flex-end; justify-content: center; background: rgb(4 8 16 / 0.68); backdrop-filter: blur(8px); }
	.fs-sheet { display: flex; flex-direction: column; width: 100%; max-width: 42rem; max-height: min(90dvh, 760px); overflow: hidden; border: 1px solid var(--border); border-radius: 1.25rem 1.25rem 0 0; background: color-mix(in srgb, var(--surface) 97%, #07101d); box-shadow: 0 -22px 70px rgb(0 0 0 / 0.45); }
	.fs-header { display: flex; align-items: center; justify-content: space-between; gap: 12px; border-bottom: 1px solid var(--border); padding: 12px 14px; }
	.fs-header h2, .fs-header p { margin: 0; }
	.fs-header h2 { color: var(--ink); font-size: 0.88rem; }
	.fs-header p { margin-top: 2px; color: var(--ink-muted); font-size: 0.66rem; }
	.fs-header code { font-family: var(--font-mono); color: #bae6fd; }
	.fs-close { display: grid; place-items: center; width: 32px; height: 32px; flex: 0 0 auto; border: 1px solid var(--border); border-radius: 999px; background: transparent; color: var(--ink-muted); cursor: pointer; }
	.fs-toolbar { display: grid; gap: 7px; border-bottom: 1px solid var(--border); padding: 9px 10px; }
	.fs-roots, .fs-crumbs { display: flex; align-items: center; gap: 5px; min-width: 0; overflow-x: auto; }
	.fs-roots button, .fs-crumbs button { display: inline-flex; align-items: center; gap: 4px; flex: 0 0 auto; border: 1px solid var(--border); border-radius: 7px; background: var(--surface-2); padding: 5px 7px; color: var(--ink-muted); font: inherit; font-size: 0.62rem; cursor: pointer; }
	.fs-search { display: flex; align-items: center; gap: 7px; border: 1px solid var(--border); border-radius: 8px; background: rgb(255 255 255 / 0.025); padding: 0 8px; color: var(--ink-muted); }
	.fs-search input { width: 100%; min-width: 0; height: 34px; border: 0; outline: 0; background: transparent; color: var(--ink); font: inherit; font-size: 0.7rem; }
	.fs-body { min-height: 0; overflow-y: auto; padding: 9px; }
	.fs-list { display: grid; gap: 5px; margin: 0; padding: 0; list-style: none; }
	.fs-entry { display: grid; grid-template-columns: auto minmax(0, 1fr) auto; align-items: center; gap: 8px; border: 1px solid var(--border); border-radius: 9px; background: var(--surface-2); padding: 7px 8px; color: #fcd34d; cursor: pointer; }
	.fs-entry > span { overflow: hidden; color: var(--ink); font-size: 0.72rem; font-weight: 600; text-overflow: ellipsis; white-space: nowrap; }
	.fs-entry > button, .fs-footer button { border: 1px solid rgb(56 189 248 / 0.32); border-radius: 7px; background: rgb(56 189 248 / 0.08); padding: 5px 7px; color: #bae6fd; font: inherit; font-size: 0.62rem; font-weight: 650; cursor: pointer; }
	.fs-empty { margin: 0; padding: 28px 12px; color: var(--ink-muted); font-size: 0.7rem; text-align: center; }
	.fs-empty--error { color: #fca5a5; }
	.fs-footer { display: flex; align-items: center; justify-content: space-between; gap: 8px; border-top: 1px solid var(--border); padding: 8px 10px; }
	.fs-footer span { min-width: 0; overflow: hidden; color: var(--ink-muted); font-family: var(--font-mono); font-size: 0.62rem; text-overflow: ellipsis; white-space: nowrap; }
	@media (min-width: 640px) { .fs-backdrop { align-items: center; padding: 16px; } .fs-sheet { border-radius: 1.25rem; } }
</style>
