// frontend/src/features/terminals/components/history-drawer.tsx
'use client';

import { Bot, Eye, History, RotateCcw, Trash2, X } from 'lucide-react';

import { TerminalProfileIcon } from '@/features/terminals/components/terminal-profile-icon';
import type { AlfaWatcher } from '@/features/terminals/hooks/use-alfa-watchers';
import type { TerminalHistoryEntry } from '@/features/terminals/hooks/use-terminal-sessions';
import { shortenCwd } from '@/features/terminals/lib/utils';

export interface HistoryDrawerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  history: TerminalHistoryEntry[];
  liveIds: Set<string>;
  watchers: AlfaWatcher[];
  onOpenEntry: (entry: TerminalHistoryEntry) => void;
  onRemoveEntry: (id: string) => void;
  onClearHistory: () => void;
}

function relativeTime(ts: number): string {
  const diff = Date.now() - ts;
  const min = Math.round(diff / 60000);
  if (min < 1) return 'just now';
  if (min < 60) return `${min}m ago`;
  const hr = Math.round(min / 60);
  if (hr < 24) return `${hr}h ago`;
  const day = Math.round(hr / 24);
  return `${day}d ago`;
}

/**
 * Terminal history — every pane that has been open, including closed ones, so
 * the user can see "what each terminal was for" and reopen/restore it. Live
 * entries focus the pane; closed entries are recreated from their stored spec.
 * Shows the owning alfa for panes that are (or were) patrol targets.
 */
export function HistoryDrawer({
  open,
  onOpenChange,
  history,
  liveIds,
  watchers,
  onOpenEntry,
  onRemoveEntry,
  onClearHistory,
}: HistoryDrawerProps) {
  if (!open) return null;

  function close() {
    onOpenChange(false);
  }

  function ownerOf(id: string): AlfaWatcher | undefined {
    return watchers.find((w) => w.watchedSessionIds.includes(id));
  }

  const sorted = history.slice().sort((a, b) => b.updatedAt - a.updatedAt);

  return (
    <div className="launcher-drawer-backdrop" onClick={close}>
      <div
        role="dialog"
        aria-modal="true"
        aria-label="Terminal history"
        onClick={(event) => event.stopPropagation()}
        className="launcher-drawer-sheet"
      >
        <div className="flex items-center justify-between gap-3 border-b border-border/70 px-4 py-3">
          <div className="flex items-center gap-2">
            <History className="h-4 w-4 text-sky-300" />
            <div>
              <p className="text-sm font-semibold text-foreground">Terminal history</p>
              <p className="text-[11px] text-muted-foreground">
                {sorted.length} entr{sorted.length === 1 ? 'y' : 'ies'} · reopen, restore, or clear
              </p>
            </div>
          </div>
          <div className="flex items-center gap-1.5">
            {sorted.length > 0 ? (
              <button
                type="button"
                onClick={onClearHistory}
                className="inline-flex h-8 items-center gap-1 rounded-md border border-border/60 px-2 text-[11px] text-muted-foreground hover:text-rose-300"
                title="Clear all history"
              >
                <Trash2 className="h-3.5 w-3.5" /> Clear
              </button>
            ) : null}
            <button
              type="button"
              onClick={close}
              className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-border/60 text-muted-foreground"
              aria-label="Close history"
            >
              <X className="h-4 w-4" />
            </button>
          </div>
        </div>

        <div className="max-h-[70vh] overflow-y-auto px-3 py-3">
          {sorted.length === 0 ? (
            <p className="px-2 py-8 text-center text-xs text-muted-foreground">
              No history yet. Terminals you open will be listed here.
            </p>
          ) : (
            <ul className="grid gap-1.5">
              {sorted.map((entry) => {
                const live = liveIds.has(entry.id);
                const owner = ownerOf(entry.id);
                const ownerLabel = owner ? owner.label?.trim() || owner.id.slice(0, 8) : undefined;
                const isAlfa = watchers.some((w) => w.id === entry.id);
                return (
                  <li
                    key={entry.id}
                    className="flex items-center gap-2 rounded-lg border border-border/50 bg-card/40 px-2.5 py-2"
                    data-live={live ? 'true' : undefined}
                  >
                    <span className="shrink-0 text-muted-foreground [&_svg]:h-4 [&_svg]:w-4">
                      <TerminalProfileIcon profile={entry.profile} />
                    </span>
                    <div className="min-w-0 flex-1">
                      <div className="flex items-center gap-1.5">
                        <span className="truncate text-xs font-semibold text-foreground">
                          {entry.title}
                        </span>
                        <span
                          className="shrink-0 rounded px-1 py-px text-[9px] font-semibold uppercase tracking-wide"
                          style={{
                            background: live ? 'rgba(52,211,153,0.16)' : 'rgba(148,163,184,0.14)',
                            color: live ? 'rgb(110,231,183)' : 'rgb(148,163,184)',
                          }}
                        >
                          {live ? 'open' : 'closed'}
                        </span>
                        {isAlfa ? (
                          <span className="alfa-pane-chip shrink-0" data-role="alfa">
                            <Bot className="h-3 w-3" /> ALFA
                          </span>
                        ) : ownerLabel ? (
                          <span className="alfa-pane-chip shrink-0" data-role="target" title={`Target of alfa "${ownerLabel}"`}>
                            <Eye className="h-3 w-3" />
                            <span className="alfa-pane-chip-owner">◄ {ownerLabel}</span>
                          </span>
                        ) : null}
                      </div>
                      <p className="truncate text-[10px] text-muted-foreground">
                        {shortenCwd(entry.cwd, 40)} · {relativeTime(entry.updatedAt)}
                      </p>
                    </div>
                    <button
                      type="button"
                      onClick={() => {
                        onOpenEntry(entry);
                        close();
                      }}
                      className="inline-flex h-8 items-center gap-1 rounded-md border border-sky-500/30 bg-sky-500/10 px-2 text-[11px] text-sky-200"
                      title={live ? 'Focus this pane' : 'Restore this terminal'}
                    >
                      <RotateCcw className="h-3.5 w-3.5" />
                      {live ? 'Focus' : 'Restore'}
                    </button>
                    <button
                      type="button"
                      onClick={() => onRemoveEntry(entry.id)}
                      className="inline-flex h-8 w-8 items-center justify-center rounded-md border border-border/60 text-muted-foreground hover:text-rose-300"
                      aria-label="Remove from history"
                      title="Remove from history"
                    >
                      <Trash2 className="h-3.5 w-3.5" />
                    </button>
                  </li>
                );
              })}
            </ul>
          )}
        </div>
      </div>
    </div>
  );
}

// frontend-svelte/src/lib/features/terminals/HistoryDrawer.svelte
<script lang="ts">
	import { Bot, Eye, History, RotateCcw, Trash2, X } from 'lucide-svelte';
	import TerminalProfileIcon from './TerminalProfileIcon.svelte';
	import { relativeHistoryTime, shortenCwd, type TerminalHistoryEntry } from './history';
	import type { AlfaWatcher } from '$lib/features/patrol/alfa';

	interface Props {
		open: boolean;
		history: TerminalHistoryEntry[];
		liveIds: ReadonlySet<string>;
		watchers?: AlfaWatcher[];
		restoring?: boolean;
		onOpenChange: (open: boolean) => void;
		onOpenEntry: (entry: TerminalHistoryEntry) => void;
		onRemoveEntry: (id: string) => void;
		onClearHistory: () => void;
	}

	let {
		open,
		history,
		liveIds,
		watchers = [],
		restoring = false,
		onOpenChange,
		onOpenEntry,
		onRemoveEntry,
		onClearHistory
	}: Props = $props();

	let sorted = $derived([...history].sort((a, b) => b.updatedAt - a.updatedAt));
</script>

<svelte:window
	onkeydown={(event) => {
		if (open && event.key === 'Escape') onOpenChange(false);
	}}
/>

{#if open}
	<div
		class="history-backdrop"
		role="presentation"
		onclick={(event) => {
			if (event.target === event.currentTarget) onOpenChange(false);
		}}
	>
		<div class="history-sheet" role="dialog" aria-modal="true" aria-label="Terminal history" tabindex="-1">
			<header class="history-header">
				<div class="history-title">
					<History size={16} />
					<div>
						<h2>Terminal history</h2>
						<p>{sorted.length} entr{sorted.length === 1 ? 'y' : 'ies'} · focus or restore</p>
					</div>
				</div>
				<div class="history-header__actions">
					{#if sorted.length > 0}
						<button type="button" class="history-clear" onclick={onClearHistory} title="Clear all history">
							<Trash2 size={13} /> Clear
						</button>
					{/if}
					<button type="button" class="history-close" onclick={() => onOpenChange(false)} aria-label="Close history">
						<X size={16} />
					</button>
				</div>
			</header>

			<div class="history-body">
				{#if sorted.length === 0}
					<p class="history-empty">No history yet. Terminals you open will be listed here.</p>
				{:else}
					<ul class="history-list">
						{#each sorted as entry (entry.id)}
							{@const live = liveIds.has(entry.id)}
							{@const selfWatcher = watchers.find((watcher) => watcher.id === entry.id)}
							{@const parentAlfa = watchers.find((watcher) => watcher.watchedSessionIds.includes(entry.id))}
							<li class="history-item" data-live={live || undefined}>
								<span class="history-profile"><TerminalProfileIcon profile={entry.profile} size={15} /></span>
								<div class="history-item__copy">
									<div class="history-item__title">
										<strong>{entry.title}</strong>
										{#if selfWatcher}<span class="history-role" data-role="alfa"><Bot size={9} /> ALFA</span>{:else if parentAlfa}<span class="history-role" data-role="target"><Eye size={9} /> TARGET</span>{/if}
										<span data-live={live || undefined}>{live ? 'open' : 'closed'}</span>
									</div>
									<p>{shortenCwd(entry.cwd, 40)} · {relativeHistoryTime(entry.updatedAt)}</p>
								</div>
								<button
									type="button"
									class="history-restore"
									disabled={restoring}
									title={live ? 'Focus this pane' : 'Restore this terminal'}
									onclick={() => {
										onOpenEntry(entry);
										onOpenChange(false);
									}}
								>
									<RotateCcw size={13} /> {live ? 'Focus' : 'Restore'}
								</button>
								<button
									type="button"
									class="history-remove"
									onclick={() => onRemoveEntry(entry.id)}
									aria-label={`Remove ${entry.title} from history`}
									title="Remove from history"
								>
									<Trash2 size={13} />
								</button>
							</li>
						{/each}
					</ul>
				{/if}
			</div>
		</div>
	</div>
{/if}

<style>
	.history-backdrop {
		position: fixed;
		inset: 0;
		z-index: 115;
		display: flex;
		align-items: flex-end;
		justify-content: center;
		background: rgb(4 8 16 / 0.62);
		backdrop-filter: blur(8px);
	}
	.history-sheet {
		display: flex;
		flex-direction: column;
		width: 100%;
		max-width: 38rem;
		max-height: min(88dvh, 760px);
		overflow: hidden;
		border: 1px solid var(--border);
		border-radius: 1.2rem 1.2rem 0 0;
		background: color-mix(in srgb, var(--surface) 97%, #07101d);
		box-shadow: 0 -20px 60px rgb(0 0 0 / 0.38);
	}
	.history-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 12px;
		padding: 12px 14px;
		border-bottom: 1px solid var(--border);
	}
	.history-title { display: flex; align-items: center; gap: 9px; color: var(--accent); }
	.history-title h2 { margin: 0; color: var(--ink); font-size: 0.88rem; }
	.history-title p { margin: 1px 0 0; color: var(--ink-muted); font-size: 0.67rem; }
	.history-header__actions { display: flex; align-items: center; gap: 6px; }
	.history-clear,
	.history-close,
	.history-restore,
	.history-remove {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		gap: 5px;
		border: 1px solid var(--border);
		background: var(--surface-2);
		color: var(--ink-muted);
		cursor: pointer;
	}
	.history-clear { min-height: 30px; border-radius: 8px; padding: 0 9px; font-size: 11px; }
	.history-close { width: 32px; height: 32px; border-radius: 999px; }
	.history-body { overflow-y: auto; padding: 12px; }
	.history-empty { margin: 0; padding: 34px 12px; text-align: center; color: var(--ink-muted); font-size: 12px; }
	.history-list { display: grid; gap: 7px; margin: 0; padding: 0; list-style: none; }
	.history-item {
		display: grid;
		grid-template-columns: auto minmax(0, 1fr) auto auto;
		align-items: center;
		gap: 8px;
		border: 1px solid var(--border);
		border-radius: 10px;
		background: color-mix(in srgb, var(--surface-2) 82%, transparent);
		padding: 8px 9px;
	}
	.history-item[data-live='true'] { border-color: rgb(52 211 153 / 0.28); }
	.history-profile { display: inline-flex; color: var(--ink-muted); }
	.history-item__copy { min-width: 0; }
	.history-item__title { display: flex; align-items: center; gap: 6px; min-width: 0; }
	.history-item__title strong { overflow: hidden; color: var(--ink); font-size: 12px; text-overflow: ellipsis; white-space: nowrap; }
	.history-item__title span {
		flex: 0 0 auto;
		border-radius: 4px;
		background: rgb(148 163 184 / 0.13);
		padding: 1px 5px;
		color: var(--ink-muted);
		font-size: 9px;
		font-weight: 700;
		text-transform: uppercase;
	}
	.history-item__title span[data-live='true'] { background: rgb(52 211 153 / 0.14); color: rgb(110 231 183); }
	.history-item__title .history-role { display: inline-flex; align-items: center; gap: 3px; letter-spacing: .04em; }
	.history-item__title .history-role[data-role='alfa'] { background: rgb(139 92 246 / .14); color: rgb(196 181 253); }
	.history-item__title .history-role[data-role='target'] { background: rgb(56 189 248 / .12); color: rgb(125 211 252); }
	.history-item__copy p { overflow: hidden; margin: 2px 0 0; color: var(--ink-muted); font-size: 10px; text-overflow: ellipsis; white-space: nowrap; }
	.history-restore { min-height: 30px; border-color: rgb(56 189 248 / 0.3); border-radius: 8px; background: rgb(56 189 248 / 0.1); padding: 0 8px; color: rgb(186 230 253); font-size: 11px; }
	.history-restore:disabled { opacity: 0.5; }
	.history-remove { width: 30px; height: 30px; border-radius: 8px; }
	.history-remove:hover, .history-clear:hover { color: rgb(253 164 175); }
	@media (min-width: 640px) {
		.history-backdrop { align-items: center; }
		.history-sheet { border-radius: 1.2rem; margin-bottom: 6vh; }
	}
	@media (max-width: 520px) {
		.history-item { grid-template-columns: auto minmax(0, 1fr) auto; }
		.history-remove { grid-column: 3; }
		.history-restore { grid-column: 1 / -1; }
	}
</style>
