// frontend/src/features/terminals/components/overview-drawer.tsx
'use client';

import { useEffect, useState } from 'react';
import { Activity, Cpu, Gauge, HardDrive, MemoryStick, Network, Server, X } from 'lucide-react';

export interface OverviewDrawerProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

interface Telemetry {
  cpu_total: number;
  cpu_cores: number[];
  ram_total: number;
  ram_used: number;
  ram_available: number;
  disk: Array<{ mount: string; total: number; used: number; available: number }>;
  network: { rx_bytes: number; tx_bytes: number; rx_rate: number; tx_rate: number };
  uptime_seconds: number;
  load_average: number[];
}

interface Overview {
  status?: string;
  runtime?: {
    terminal_sessions: number;
    terminal_profiles: number;
    environments: number;
    agent_profiles: number;
  };
  telemetry?: Telemetry | null;
}

function fmtBytes(n: number): string {
  if (!n || n < 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB', 'TB'];
  const i = Math.min(units.length - 1, Math.floor(Math.log(n) / Math.log(1024)));
  return `${(n / 1024 ** i).toFixed(i === 0 ? 0 : 1)} ${units[i]}`;
}

function fmtUptime(s: number): string {
  if (!s) return '—';
  const d = Math.floor(s / 86400);
  const h = Math.floor((s % 86400) / 3600);
  const m = Math.floor((s % 3600) / 60);
  if (d > 0) return `${d}d ${h}h`;
  if (h > 0) return `${h}h ${m}m`;
  return `${m}m`;
}

function toneFor(pct: number): string {
  if (pct >= 90) return 'bg-rose-400';
  if (pct >= 70) return 'bg-amber-400';
  return 'bg-emerald-400';
}

function Bar({ pct }: { pct: number }) {
  const clamped = Math.max(0, Math.min(100, pct));
  return (
    <div className="h-1.5 w-full overflow-hidden rounded-full bg-border/50">
      <div className={`h-full rounded-full ${toneFor(clamped)}`} style={{ width: `${clamped}%` }} />
    </div>
  );
}

/**
 * Read-only host overview. Surfaces the telemetry the agent already samples
 * every ~15s (CPU / RAM / disk / load / net / uptime) so the operator doesn't
 * have to open a shell and run htop. Polls every 5s while open.
 */
export function OverviewDrawer({ open, onOpenChange }: OverviewDrawerProps) {
  const [data, setData] = useState<Overview | null>(null);
  const [error, setError] = useState(false);

  useEffect(() => {
    if (!open) return;
    let active = true;
    const load = async () => {
      try {
        const res = await fetch('/api/overview', { cache: 'no-store' });
        if (!res.ok) throw new Error('bad');
        const json = (await res.json()) as Overview;
        if (active) {
          setData(json);
          setError(false);
        }
      } catch {
        if (active) setError(true);
      }
    };
    void load();
    const id = setInterval(load, 5000);
    return () => {
      active = false;
      clearInterval(id);
    };
  }, [open]);

  if (!open) return null;

  const t = data?.telemetry ?? null;
  const ramPct = t && t.ram_total ? (t.ram_used / t.ram_total) * 100 : 0;

  return (
    <div className="launcher-drawer-backdrop" onClick={() => onOpenChange(false)}>
      <div
        role="dialog"
        aria-modal="true"
        aria-label="System overview"
        onClick={(event) => event.stopPropagation()}
        className="launcher-drawer-sheet"
      >
        <div className="flex items-center justify-between gap-3 border-b border-border/70 px-4 py-3">
          <div className="flex items-center gap-2">
            <Gauge className="h-4 w-4 text-sky-300" />
            <div>
              <p className="text-sm font-semibold text-foreground">System overview</p>
              <p className="text-[11px] text-muted-foreground">
                {error
                  ? 'Agent unreachable'
                  : t
                    ? `Uptime ${fmtUptime(t.uptime_seconds)} · live`
                    : 'Loading…'}
              </p>
            </div>
          </div>
          <button
            type="button"
            onClick={() => onOpenChange(false)}
            className="inline-flex h-9 w-9 items-center justify-center rounded-full border border-border/60 text-muted-foreground"
            aria-label="Close overview"
          >
            <X className="h-4 w-4" />
          </button>
        </div>

        <div className="max-h-[70vh] space-y-3 overflow-y-auto px-3 py-3">
          {error ? (
            <p className="px-2 py-6 text-center text-xs text-muted-foreground">
              Couldn&apos;t reach the agent. Check it&apos;s running on the host
              (<span className="font-mono">systemctl status vps-control-room-agent</span>).
            </p>
          ) : !t ? (
            <p className="px-2 py-6 text-center text-xs text-muted-foreground">Loading host metrics…</p>
          ) : (
            <>
              <section className="rounded-lg border border-border/50 bg-card/40 px-3 py-2.5">
                <div className="mb-1.5 flex items-center justify-between text-xs">
                  <span className="flex items-center gap-1.5 font-medium text-foreground">
                    <Cpu className="h-3.5 w-3.5 text-sky-300" /> CPU
                  </span>
                  <span className="font-mono text-muted-foreground">
                    {t.cpu_total.toFixed(0)}% · {t.cpu_cores.length} cores
                  </span>
                </div>
                <Bar pct={t.cpu_total} />
              </section>

              <section className="rounded-lg border border-border/50 bg-card/40 px-3 py-2.5">
                <div className="mb-1.5 flex items-center justify-between text-xs">
                  <span className="flex items-center gap-1.5 font-medium text-foreground">
                    <MemoryStick className="h-3.5 w-3.5 text-violet-300" /> Memory
                  </span>
                  <span className="font-mono text-muted-foreground">
                    {fmtBytes(t.ram_used)} / {fmtBytes(t.ram_total)}
                  </span>
                </div>
                <Bar pct={ramPct} />
              </section>

              <section className="grid grid-cols-2 gap-2">
                <div className="rounded-lg border border-border/50 bg-card/40 px-3 py-2.5">
                  <p className="flex items-center gap-1.5 text-[11px] font-medium text-muted-foreground">
                    <Activity className="h-3.5 w-3.5 text-amber-300" /> Load avg
                  </p>
                  <p className="mt-1 font-mono text-sm text-foreground">
                    {t.load_average.map((n) => n.toFixed(2)).join('  ')}
                  </p>
                </div>
                <div className="rounded-lg border border-border/50 bg-card/40 px-3 py-2.5">
                  <p className="flex items-center gap-1.5 text-[11px] font-medium text-muted-foreground">
                    <Server className="h-3.5 w-3.5 text-emerald-300" /> Uptime
                  </p>
                  <p className="mt-1 font-mono text-sm text-foreground">{fmtUptime(t.uptime_seconds)}</p>
                </div>
              </section>

              <section className="rounded-lg border border-border/50 bg-card/40 px-3 py-2.5">
                <div className="flex items-center justify-between text-xs">
                  <span className="flex items-center gap-1.5 font-medium text-foreground">
                    <Network className="h-3.5 w-3.5 text-cyan-300" /> Network
                  </span>
                  <span className="font-mono text-muted-foreground">
                    ↓ {fmtBytes(t.network.rx_rate)}/s · ↑ {fmtBytes(t.network.tx_rate)}/s
                  </span>
                </div>
              </section>

              {t.disk.length > 0 ? (
                <section className="rounded-lg border border-border/50 bg-card/40 px-3 py-2.5">
                  <p className="mb-2 flex items-center gap-1.5 text-xs font-medium text-foreground">
                    <HardDrive className="h-3.5 w-3.5 text-slate-300" /> Disk
                  </p>
                  <ul className="grid gap-2">
                    {t.disk.map((d) => {
                      const pct = d.total ? (d.used / d.total) * 100 : 0;
                      return (
                        <li key={d.mount}>
                          <div className="mb-1 flex items-center justify-between text-[11px]">
                            <span className="font-mono text-muted-foreground">{d.mount}</span>
                            <span className="font-mono text-muted-foreground">
                              {fmtBytes(d.used)} / {fmtBytes(d.total)}
                            </span>
                          </div>
                          <Bar pct={pct} />
                        </li>
                      );
                    })}
                  </ul>
                </section>
              ) : null}

              {data?.runtime ? (
                <section className="grid grid-cols-2 gap-2 px-1 pt-1 text-[11px] text-muted-foreground">
                  <span>
                    Sessions: <span className="font-mono text-foreground">{data.runtime.terminal_sessions}</span>
                  </span>
                  <span>
                    Agents: <span className="font-mono text-foreground">{data.runtime.agent_profiles}</span>
                  </span>
                  <span>
                    Profiles: <span className="font-mono text-foreground">{data.runtime.terminal_profiles}</span>
                  </span>
                  <span>
                    Envs: <span className="font-mono text-foreground">{data.runtime.environments}</span>
                  </span>
                </section>
              ) : null}
            </>
          )}
        </div>
      </div>
    </div>
  );
}

// frontend-svelte/src/lib/features/terminals/OverviewDrawer.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { Activity, Cpu, Gauge, HardDrive, MemoryStick, Network, Server, X } from 'lucide-svelte';

	import {
		formatBytes,
		formatUptime,
		usagePercent,
		usageTone,
		type HostOverview
	} from './overview';

	interface Props {
		onClose: () => void;
	}

	let { onClose }: Props = $props();
	let data = $state<HostOverview | null>(null);
	let loading = $state(true);
	let error = $state(false);
	let telemetry = $derived(data?.telemetry ?? null);
	let ramPercent = $derived(telemetry ? usagePercent(telemetry.ram_used, telemetry.ram_total) : 0);

	async function load(): Promise<void> {
		try {
			const response = await fetch('/api/overview', { cache: 'no-store' });
			if (!response.ok) throw new Error(`Overview ${response.status}`);
			data = (await response.json()) as HostOverview;
			error = false;
		} catch {
			error = true;
		} finally {
			loading = false;
		}
	}

	onMount(() => {
		void load();
		const interval = window.setInterval(() => void load(), 5000);
		return () => window.clearInterval(interval);
	});
</script>

<svelte:window onkeydown={(event) => event.key === 'Escape' && onClose()} />

<button class="overview-backdrop" type="button" aria-label="Close system overview" onclick={onClose}></button>
<div class="overview-sheet" role="dialog" aria-modal="true" aria-label="System overview">
	<header class="overview-header">
		<div class="overview-title">
			<Gauge size={17} />
			<div>
				<strong>System overview</strong>
				<small>
					{#if error}
						Agent unreachable
					{:else if telemetry}
						Uptime {formatUptime(telemetry.uptime_seconds)} · live
					{:else}
						Loading…
					{/if}
				</small>
			</div>
		</div>
		<button class="overview-close" type="button" aria-label="Close overview" onclick={onClose}><X size={16} /></button>
	</header>

	<div class="overview-body">
		{#if error && !telemetry}
			<p class="overview-empty">Couldn’t reach the agent. Check the host agent service.</p>
		{:else if loading && !telemetry}
			<p class="overview-empty">Loading host metrics…</p>
		{:else if telemetry}
			<section class="metric-card">
				<div class="metric-row">
					<span class="metric-label"><Cpu size={14} /> CPU</span>
					<span class="metric-value">{telemetry.cpu_total.toFixed(0)}% · {telemetry.cpu_cores.length} cores</span>
				</div>
				<div class="usage-bar" data-tone={usageTone(telemetry.cpu_total)}><span style:width={`${usagePercent(telemetry.cpu_total, 100)}%`}></span></div>
			</section>

			<section class="metric-card">
				<div class="metric-row">
					<span class="metric-label"><MemoryStick size={14} /> Memory</span>
					<span class="metric-value">{formatBytes(telemetry.ram_used)} / {formatBytes(telemetry.ram_total)}</span>
				</div>
				<div class="usage-bar" data-tone={usageTone(ramPercent)}><span style:width={`${ramPercent}%`}></span></div>
			</section>

			<section class="metric-grid">
				<div class="metric-card metric-card--compact">
					<span class="metric-label"><Activity size={14} /> Load avg</span>
					<strong class="metric-big">{telemetry.load_average.map((value) => value.toFixed(2)).join('  ')}</strong>
				</div>
				<div class="metric-card metric-card--compact">
					<span class="metric-label"><Server size={14} /> Uptime</span>
					<strong class="metric-big">{formatUptime(telemetry.uptime_seconds)}</strong>
				</div>
			</section>

			<section class="metric-card">
				<div class="metric-row">
					<span class="metric-label"><Network size={14} /> Network</span>
					<span class="metric-value">↓ {formatBytes(telemetry.network.rx_rate)}/s · ↑ {formatBytes(telemetry.network.tx_rate)}/s</span>
				</div>
			</section>

			{#if telemetry.disk.length > 0}
				<section class="metric-card">
					<span class="metric-label metric-label--heading"><HardDrive size={14} /> Disk</span>
					<ul class="disk-list">
						{#each telemetry.disk as disk (disk.mount)}
							{@const percent = usagePercent(disk.used, disk.total)}
							<li>
								<div class="metric-row metric-row--small">
									<span class="metric-value">{disk.mount}</span>
									<span class="metric-value">{formatBytes(disk.used)} / {formatBytes(disk.total)}</span>
								</div>
								<div class="usage-bar" data-tone={usageTone(percent)}><span style:width={`${percent}%`}></span></div>
							</li>
						{/each}
					</ul>
				</section>
			{/if}

			{#if data?.runtime}
				<section class="runtime-grid" aria-label="Runtime counts">
					<span>Sessions <strong>{data.runtime.terminal_sessions}</strong></span>
					<span>Agents <strong>{data.runtime.agent_profiles}</strong></span>
					<span>Profiles <strong>{data.runtime.terminal_profiles}</strong></span>
					<span>Envs <strong>{data.runtime.environments}</strong></span>
				</section>
			{/if}
		{/if}
	</div>
</div>

<style>
	.overview-backdrop {
		position: fixed;
		inset: 0;
		z-index: 90;
		border: 0;
		background: rgb(3 7 18 / 0.72);
		backdrop-filter: blur(6px);
	}
	.overview-sheet {
		position: fixed;
		z-index: 91;
		right: 50%;
		top: 50%;
		display: flex;
		width: min(540px, calc(100vw - 24px));
		max-height: min(760px, calc(100dvh - 24px));
		transform: translate(50%, -50%);
		flex-direction: column;
		overflow: hidden;
		border: 1px solid var(--border);
		border-radius: 16px;
		background: color-mix(in srgb, var(--surface) 97%, #07101d);
		box-shadow: 0 24px 80px rgb(0 0 0 / 0.5);
	}
	.overview-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: 12px;
		padding: 12px 14px;
		border-bottom: 1px solid var(--border);
	}
	.overview-title { display: flex; min-width: 0; align-items: center; gap: 9px; color: var(--ink); }
	.overview-title > div { display: grid; min-width: 0; }
	.overview-title strong { font-size: 13px; }
	.overview-title small { color: var(--ink-muted); font-size: 10px; }
	.overview-close {
		display: inline-flex;
		width: 32px;
		height: 32px;
		flex: 0 0 auto;
		align-items: center;
		justify-content: center;
		border: 1px solid var(--border);
		border-radius: 999px;
		background: transparent;
		color: var(--ink-muted);
		cursor: pointer;
	}
	.overview-body { display: grid; min-height: 0; gap: 10px; overflow-y: auto; padding: 12px; }
	.overview-empty { margin: 0; padding: 28px 12px; text-align: center; color: var(--ink-muted); font-size: 11px; }
	.metric-card {
		display: grid;
		gap: 8px;
		border: 1px solid var(--border);
		border-radius: 10px;
		background: color-mix(in srgb, var(--surface-2) 82%, transparent);
		padding: 10px 11px;
	}
	.metric-card--compact { min-width: 0; }
	.metric-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 8px; }
	.metric-row { display: flex; min-width: 0; align-items: center; justify-content: space-between; gap: 10px; }
	.metric-row--small { font-size: 10px; }
	.metric-label { display: inline-flex; align-items: center; gap: 6px; color: var(--ink); font-size: 11px; font-weight: 600; }
	.metric-label--heading { margin-bottom: 2px; }
	.metric-value { min-width: 0; overflow: hidden; color: var(--ink-muted); font-family: var(--font-mono); font-size: 10px; text-overflow: ellipsis; white-space: nowrap; }
	.metric-big { margin-top: 2px; color: var(--ink); font-family: var(--font-mono); font-size: 13px; font-weight: 500; }
	.usage-bar { height: 6px; overflow: hidden; border-radius: 999px; background: color-mix(in srgb, var(--border) 62%, transparent); }
	.usage-bar span { display: block; height: 100%; border-radius: inherit; background: #34d399; transition: width 180ms ease; }
	.usage-bar[data-tone='warn'] span { background: #fbbf24; }
	.usage-bar[data-tone='danger'] span { background: #fb7185; }
	.disk-list { display: grid; gap: 10px; margin: 0; padding: 0; list-style: none; }
	.runtime-grid { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 6px 12px; padding: 2px 4px 0; color: var(--ink-muted); font-size: 10px; }
	.runtime-grid span { display: flex; justify-content: space-between; gap: 8px; }
	.runtime-grid strong { color: var(--ink); font-family: var(--font-mono); font-weight: 500; }
	@media (max-width: 640px) {
		.overview-sheet {
			right: 0;
			top: auto;
			bottom: 0;
			width: 100%;
			max-height: calc(100dvh - max(8px, env(safe-area-inset-top)));
			transform: none;
			border-right: 0;
			border-bottom: 0;
			border-left: 0;
			border-radius: 18px 18px 0 0;
			padding-bottom: env(safe-area-inset-bottom);
		}
		.metric-grid { grid-template-columns: 1fr; }
	}
</style>
