// frontend/src/features/terminals/components/session-color-picker.tsx
'use client';

import { useEffect, useRef, useState } from 'react';

import { SESSION_COLOR_PALETTE } from '@/features/terminals/hooks/use-session-colors';

interface SessionColorPickerProps {
  sessionId: string;
  color: string;
  hasOverride: boolean;
  onPick: (color: string) => void;
  onClear: () => void;
  /** When true the swatch is read-only — used by target panes that
   *  inherit their color from a parent alfa watcher. */
  disabled?: boolean;
  /** Override the swatch's tooltip (e.g. to explain inheritance). */
  title?: string;
  /** Controlled open state — lets the mobile cluster drive the palette. */
  open?: boolean;
  onOpenChange?: (open: boolean) => void;
  /** Hide the swatch trigger and render the palette as a centered sheet. */
  hideTrigger?: boolean;
}

/**
 * Small color swatch + popover palette. Click toggles the palette, picking
 * a swatch dispatches `onPick`; the dotted swatch dispatches `onClear` to
 * fall back to the hash-derived default.
 */
export function SessionColorPicker({
  sessionId,
  color,
  hasOverride,
  onPick,
  onClear,
  disabled = false,
  title,
  open: controlledOpen,
  onOpenChange,
  hideTrigger = false,
}: SessionColorPickerProps) {
  const [internalOpen, setInternalOpen] = useState(false);
  const open = controlledOpen ?? internalOpen;
  const setOpen = (value: boolean | ((prev: boolean) => boolean)) => {
    const next = typeof value === 'function' ? value(open) : value;
    if (onOpenChange) onOpenChange(next);
    else setInternalOpen(next);
  };
  const ref = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (!open) return;
    function handleClick(event: MouseEvent) {
      if (!ref.current?.contains(event.target as Node)) setOpen(false);
    }
    // Sheet mode closes via its own backdrop.
    if (!hideTrigger) document.addEventListener('mousedown', handleClick);
    return () => document.removeEventListener('mousedown', handleClick);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, hideTrigger]);

  const palette = (
    <>
      {SESSION_COLOR_PALETTE.map((swatch) => (
        <button
          key={swatch}
          type="button"
          style={{ background: swatch }}
          data-active={color === swatch || undefined}
          onClick={() => {
            onPick(swatch);
            setOpen(false);
          }}
        />
      ))}
      {hasOverride ? (
        <button
          type="button"
          data-empty
          className="session-color-swatch"
          title="Reset to default"
          onClick={() => {
            onClear();
            setOpen(false);
          }}
        />
      ) : null}
    </>
  );

  return (
    <div ref={ref} style={{ position: 'relative', display: 'inline-block' }}>
      {hideTrigger ? null : (
        <button
          type="button"
          className="session-color-swatch"
          data-disabled={disabled || undefined}
          disabled={disabled}
          style={{ ['--session-color' as string]: color }}
          title={title ?? `Color for ${sessionId.slice(0, 8)} — click to change`}
          onClick={(event) => {
            event.preventDefault();
            event.stopPropagation();
            if (disabled) return;
            setOpen((value) => !value);
          }}
        />
      )}

      {open ? (
        hideTrigger ? (
          <div className="pane-sheet-overlay" role="dialog" aria-modal="true">
            <div className="pane-sheet-backdrop" onClick={() => setOpen(false)} />
            <div
              className="pane-sheet-panel session-color-picker session-color-picker-sheet"
              onClick={(event) => event.stopPropagation()}
            >
              {palette}
            </div>
          </div>
        ) : (
          <div
            className="session-color-picker"
            style={{ top: 'calc(100% + 4px)', left: 0 }}
            onClick={(event) => event.stopPropagation()}
          >
            {palette}
          </div>
        )
      ) : null}
    </div>
  );
}

// frontend-svelte/src/lib/features/terminals/SessionColorPicker.svelte
<script lang="ts">
	import { RotateCcw } from 'lucide-svelte';
	import { SESSION_COLOR_PALETTE } from './session-colors';

	interface Props {
		sessionId: string;
		color: string;
		hasOverride: boolean;
		onPick: (color: string) => void;
		onClear: () => void;
		disabled?: boolean;
		title?: string;
		open?: boolean;
		onOpenChange?: (open: boolean) => void;
		hideTrigger?: boolean;
	}

	let {
		sessionId,
		color,
		hasOverride,
		onPick,
		onClear,
		disabled = false,
		title,
		open: controlledOpen,
		onOpenChange,
		hideTrigger = false
	}: Props = $props();

	let internalOpen = $state(false);
	let wrapper: HTMLDivElement | undefined = $state();
	let open = $derived(controlledOpen ?? internalOpen);

	function setOpen(next: boolean): void {
		if (onOpenChange) onOpenChange(next);
		else internalOpen = next;
	}

	function pick(swatch: string): void {
		onPick(swatch);
		setOpen(false);
	}

	function clear(): void {
		onClear();
		setOpen(false);
	}
</script>

<svelte:window
	onmousedown={(event) => {
		if (!open || hideTrigger) return;
		if (event.target instanceof Node && !wrapper?.contains(event.target)) setOpen(false);
	}}
	onkeydown={(event) => {
		if (open && event.key === 'Escape') setOpen(false);
	}}
/>

<div class="session-color" bind:this={wrapper}>
	{#if !hideTrigger}
		<button
			type="button"
			class="session-color__trigger"
			style:--session-color={color}
			disabled={disabled}
			data-disabled={disabled || undefined}
			aria-label={`Change color for ${sessionId.slice(0, 8)}`}
			aria-expanded={open}
			aria-haspopup="dialog"
			title={title ?? `Color for ${sessionId.slice(0, 8)} — click to change`}
			onclick={(event) => {
				event.preventDefault();
				event.stopPropagation();
				if (!disabled) setOpen(!open);
			}}
		></button>
	{/if}

	{#if open}
		{#if hideTrigger}
			<div class="session-color__overlay" role="dialog" aria-modal="true" aria-label="Session color">
				<button type="button" class="session-color__backdrop" aria-label="Close color picker" onclick={() => setOpen(false)}></button>
				<div class="session-color__palette session-color__palette--sheet">
					{#each SESSION_COLOR_PALETTE as swatch (swatch)}
						<button
							type="button"
							class="session-color__option"
							style:background={swatch}
							data-active={color === swatch || undefined}
							aria-label={`Use color ${swatch}`}
							onclick={() => pick(swatch)}
						></button>
					{/each}
					{#if hasOverride}
						<button type="button" class="session-color__option session-color__reset" aria-label="Reset session color" onclick={clear}>
							<RotateCcw size={13} />
						</button>
					{/if}
				</div>
			</div>
		{:else}
			<div class="session-color__palette" role="dialog" aria-label="Session color">
				{#each SESSION_COLOR_PALETTE as swatch (swatch)}
					<button
						type="button"
						class="session-color__option"
						style:background={swatch}
						data-active={color === swatch || undefined}
						aria-label={`Use color ${swatch}`}
						onclick={() => pick(swatch)}
					></button>
				{/each}
				{#if hasOverride}
					<button type="button" class="session-color__option session-color__reset" aria-label="Reset session color" onclick={clear}>
						<RotateCcw size={13} />
					</button>
				{/if}
			</div>
		{/if}
	{/if}
</div>

<style>
	.session-color { position: relative; display: inline-flex; flex: 0 0 auto; }
	.session-color__trigger {
		width: 13px;
		height: 13px;
		padding: 0;
		border: 1px solid color-mix(in srgb, var(--session-color) 70%, white 30%);
		border-radius: 999px;
		background: var(--session-color);
		box-shadow: 0 0 0 2px color-mix(in srgb, var(--session-color) 18%, transparent);
		cursor: pointer;
	}
	.session-color__trigger[data-disabled='true'] { cursor: default; opacity: 0.55; }
	.session-color__palette {
		position: absolute;
		top: calc(100% + 7px);
		right: 0;
		z-index: 80;
		display: grid;
		grid-template-columns: repeat(4, 24px);
		gap: 6px;
		padding: 8px;
		border: 1px solid var(--border);
		border-radius: 10px;
		background: color-mix(in srgb, var(--surface) 96%, #07101d);
		box-shadow: 0 14px 36px rgb(0 0 0 / 0.4);
	}
	.session-color__option {
		display: grid;
		width: 24px;
		height: 24px;
		place-items: center;
		padding: 0;
		border: 2px solid transparent;
		border-radius: 999px;
		cursor: pointer;
	}
	.session-color__option[data-active='true'] { border-color: white; box-shadow: 0 0 0 1px rgb(255 255 255 / 0.3); }
	.session-color__reset { background: var(--surface-2); color: var(--ink-muted); }
	.session-color__overlay { position: fixed; inset: 0; z-index: 120; display: grid; place-items: center; }
	.session-color__backdrop { position: absolute; inset: 0; border: 0; background: rgb(4 8 16 / 0.62); backdrop-filter: blur(7px); }
	.session-color__palette--sheet { position: relative; top: auto; right: auto; grid-template-columns: repeat(4, 30px); gap: 8px; padding: 12px; }
	.session-color__palette--sheet .session-color__option { width: 30px; height: 30px; }
</style>
